MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.14            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
openssl:
  - '1.1.1'
  - '3'
  - '3'
libcurl:
  - 7
  - 7
  - 8
krb5:
  - 1.20
  - 1.20
  - 1.21
zip_keys:
  - 'openssl'
  - 'libcurl'
  - 'krb5'
